/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    DictBottomPanel: typeof import('./../components/dictBottomPanel.vue')['default']
    DictDictPanel: typeof import('./../components/dictDictPanel.vue')['default']
    DictInputPanel: typeof import('./../components/dictInputPanel.vue')['default']
    DictTitlebar: typeof import('./../components/dictTitlebar.vue')['default']
    DictWordPanel: typeof import('./../components/dictWordPanel.vue')['default']
    ElAutocomplete: typeof import('element-plus/es')['ElAutocomplete']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    ReciteReciteDialog: typeof import('./../components/reciteReciteDialog.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    StudyTestMode: typeof import('./../components/studyTestMode.vue')['default']
    UserLevelDialog: typeof import('./../components/userLevelDialog.vue')['default']
  }
}
